"use client";

import { FormEvent, useState } from "react";
import type { ContactItemRecord, FaqRecord } from "@/lib/content-types";

export default function ContactContent({ items, faqs }: { items: ContactItemRecord[]; faqs: FaqRecord[] }) {
  const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" });
  const [sent, setSent] = useState(false);
  const emailItem = items.find((item) => item.label.toLowerCase().includes("email"));
  const recipient = emailItem?.value || "mathsclub@iitism.ac.in";
  function submit(event: FormEvent) {
    event.preventDefault();
    window.location.href = `mailto:${recipient}?subject=${encodeURIComponent(form.subject)}&body=${encodeURIComponent(`Name: ${form.name}\nEmail: ${form.email}\n\nMessage:\n${form.message}`)}`;
    setSent(true);
  }
  return <>
    <section className="pt-36 pb-20 px-6 relative overflow-hidden math-grid"><div className="absolute inset-0" style={{ background: "radial-gradient(ellipse 50% 80% at 50% 0%, rgba(212,168,67,0.07) 0%, transparent 70%)" }} /><div className="relative z-10 max-w-5xl mx-auto"><p className="font-mono text-[#d4a843]/60 text-xs tracking-[0.3em] uppercase mb-4">Reach Out</p><h1 className="font-display text-6xl md:text-8xl font-light text-[#e8e8e0] leading-tight mb-6">Get in<br /><span className="text-[#d4a843] italic">Touch</span></h1><div className="section-divider w-32 mb-8" /><p className="font-sans text-lg text-[#e8e8e0]/60 max-w-2xl leading-relaxed">Whether you want to join, collaborate, invite us to your event, or just talk mathematics—we&apos;re always listening.</p></div></section>
    <section className="py-16 px-6"><div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-16"><div>{!sent ? <form onSubmit={submit} className="space-y-5">{([{ id: "name", label: "Your Name", type: "text", placeholder: "Leonhard Euler" }, { id: "email", label: "Email Address", type: "email", placeholder: "you@iitism.ac.in" }, { id: "subject", label: "Subject", type: "text", placeholder: "I want to join / Collaboration / ..." }] as const).map((field) => <label key={field.id} className="block"><span className="block font-mono text-[10px] text-[#d4a843]/60 tracking-widest uppercase mb-2">{field.label}</span><input type={field.type} value={form[field.id]} onChange={(event) => setForm({ ...form, [field.id]: event.target.value })} placeholder={field.placeholder} required className="w-full bg-[#0d1f35]/60 border border-[#d4a843]/20 text-[#e8e8e0] placeholder-[#e8e8e0]/20 text-sm px-4 py-3 focus:outline-none focus:border-[#d4a843]/60" /></label>)}<label className="block"><span className="block font-mono text-[10px] text-[#d4a843]/60 tracking-widest uppercase mb-2">Message</span><textarea value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} rows={5} required className="w-full bg-[#0d1f35]/60 border border-[#d4a843]/20 text-[#e8e8e0] text-sm px-4 py-3 focus:outline-none focus:border-[#d4a843]/60 resize-none" /></label><button className="w-full bg-[#d4a843] text-[#0a1628] font-bold text-sm tracking-widest uppercase py-4 hover:bg-[#f0d080]">Send Message</button></form> : <div className="border border-[#d4a843]/30 bg-[#0d1f35]/60 p-10 text-center border-glow"><div className="font-display text-6xl text-[#d4a843] mb-4">✓</div><h2 className="font-serif text-2xl mb-3">Email prepared</h2><p className="text-sm text-[#e8e8e0]/50">Your email app should now be open. Send the prepared message from there.</p><button onClick={() => setSent(false)} className="mt-6 text-xs text-[#d4a843] tracking-widest uppercase">Send another →</button></div>}</div>
      <div className="space-y-8"><div className="space-y-8">{items.map((item) => <div key={item.id} className="flex gap-4"><div className="text-2xl mt-0.5">{item.icon}</div><div><div className="font-mono text-[10px] text-[#d4a843]/60 tracking-widest uppercase mb-1">{item.label}</div>{item.url ? <a href={item.url} className="font-sans text-sm text-[#e8e8e0]/60 hover:text-[#d4a843] whitespace-pre-line">{item.value}</a> : <div className="font-sans text-sm text-[#e8e8e0]/60 leading-relaxed whitespace-pre-line">{item.value}</div>}</div></div>)}</div><div className="border-t border-[#d4a843]/15 pt-8"><h2 className="font-serif text-lg font-semibold mb-5">Frequently Asked</h2><div className="space-y-4">{faqs.map((faq) => <article key={faq.id} className="border border-[#d4a843]/10 bg-[#0d1f35]/30 p-4"><h3 className="font-serif text-sm font-semibold mb-1">{faq.question}</h3><p className="font-sans text-xs text-[#e8e8e0]/50 leading-relaxed">{faq.answer}</p></article>)}</div></div></div>
    </div></section>
  </>;
}
