"use client";

import { FormEvent, useEffect, useState } from "react";
import type { ContactItemRecord, FaqRecord, QotdRecord, ResourceKind, ResourceRecord } from "@/lib/content-types";

const input = "w-full rounded-sm border border-[#d4a843]/20 bg-[#081526] px-3 py-2.5 text-sm text-[#e8e8e0] outline-none focus:border-[#d4a843]/70";
const label = "block text-[11px] uppercase tracking-widest text-[#e8e8e0]/50 mb-1.5";
const save = "w-full bg-[#d4a843] text-[#0a1628] py-3 text-xs font-semibold uppercase tracking-widest disabled:opacity-40";

async function request(url: string, options?: RequestInit) {
  const response = await fetch(url, options); const data = await response.json();
  if (!response.ok) throw new Error(data.error || "Something went wrong.");
  return data;
}

function Message({ text }: { text: string }) { return text ? <p className="mb-5 border border-[#d4a843]/20 p-3 text-sm text-[#e8e8e0]/70">{text}</p> : null; }
function Actions({ edit, remove }: { edit: () => void; remove: () => void }) { return <div className="flex gap-2 shrink-0"><button onClick={edit} className="border border-[#d4a843]/30 px-3 py-2 text-[10px] uppercase tracking-widest text-[#d4a843]">Edit</button><button onClick={remove} className="border border-red-400/20 px-3 py-2 text-[10px] uppercase tracking-widest text-red-300/70">Delete</button></div>; }

export function ResourcesManager({ configured }: { configured: boolean }) {
  const blank = { kind: "book" as ResourceKind, title: "", subtitle: "", description: "", url: "", topic: "", level: "Beginner", sort_order: 1 };
  const [form, setForm] = useState(blank); const [id, setId] = useState<string | null>(null); const [items, setItems] = useState<ResourceRecord[]>([]); const [message, setMessage] = useState("");
  const load = () => request("/api/resources").then((data) => setItems(data.items)).catch((error) => setMessage(error.message));
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); try { await request("/api/resources", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(id ? { id, ...form, url: form.url || null } : { ...form, url: form.url || null }) }); setForm(blank); setId(null); await load(); setMessage("Resource saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save."); } }
  async function remove(item: ResourceRecord) { if (!confirm(`Delete ${item.title}?`)) return; try { await request(`/api/resources?id=${item.id}`, { method: "DELETE" }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not delete."); } }
  return <div className="grid lg:grid-cols-[minmax(0,420px)_1fr] gap-8 items-start"><form onSubmit={submit} className="border border-[#d4a843]/20 bg-[#0d1f35]/60 p-6 lg:sticky lg:top-24"><h2 className="font-serif text-2xl mb-5">{id ? "Edit resource" : "Add a resource"}</h2><Message text={message} /><div className="space-y-4"><Field name="Type"><select className={input} value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value as ResourceKind })}><option value="book">Book</option><option value="link">Online resource</option><option value="archive">Exam / problem archive</option></select></Field><Field name="Title"><input className={input} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></Field>{form.kind === "book" ? <><Field name="Author"><input className={input} value={form.subtitle} onChange={(e) => setForm({ ...form, subtitle: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field name="Topic"><input className={input} value={form.topic} onChange={(e) => setForm({ ...form, topic: e.target.value })} /></Field><Field name="Level"><select className={input} value={form.level} onChange={(e) => setForm({ ...form, level: e.target.value })}><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Expert</option></select></Field></div></> : <><Field name="Web address"><input className={input} type="url" value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} required /></Field><Field name="Description"><textarea className={`${input} min-h-24`} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field></>}<Field name="Display order"><input className={input} type="number" min="0" value={form.sort_order} onChange={(e) => setForm({ ...form, sort_order: Number(e.target.value) })} /></Field></div><button disabled={!configured} className={`${save} mt-6`}>{id ? "Save changes" : "Add resource"}</button>{id && <button type="button" onClick={() => { setId(null); setForm(blank); }} className="w-full mt-2 py-2 text-xs uppercase text-[#e8e8e0]/50">Cancel</button>}</form><div className="space-y-4"><h2 className="font-serif text-2xl">All resources ({items.length})</h2>{items.map((item) => <article key={item.id} className="border border-[#d4a843]/15 bg-[#0d1f35]/40 p-5 flex justify-between gap-4"><div><div className="text-[10px] uppercase tracking-widest text-[#d4a843] mb-2">{item.kind}</div><h3 className="font-serif text-xl">{item.title}</h3><p className="text-sm text-[#e8e8e0]/40">{item.kind === "book" ? item.subtitle : item.description}</p></div><Actions edit={() => { setId(item.id); setForm({ kind: item.kind, title: item.title, subtitle: item.subtitle, description: item.description, url: item.url || "", topic: item.topic, level: item.level, sort_order: item.sort_order }); scrollTo({ top: 0, behavior: "smooth" }); }} remove={() => remove(item)} /></article>)}</div></div>;
}

export function ContactManager({ configured }: { configured: boolean }) {
  const blankItem = { icon: "📍", label: "", value: "", url: "", sort_order: 1 }; const blankFaq = { question: "", answer: "", sort_order: 1 };
  const [items, setItems] = useState<ContactItemRecord[]>([]); const [faqs, setFaqs] = useState<FaqRecord[]>([]); const [item, setItem] = useState(blankItem); const [faq, setFaq] = useState(blankFaq); const [itemId, setItemId] = useState<string | null>(null); const [faqId, setFaqId] = useState<string | null>(null); const [message, setMessage] = useState("");
  const load = () => request("/api/contact").then((data) => { setItems(data.items); setFaqs(data.faqs); }).catch((error) => setMessage(error.message)); useEffect(() => { void load(); }, []);
  async function saveItem(event: FormEvent) { event.preventDefault(); try { await request("/api/contact", { method: itemId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(itemId ? { id: itemId, entity: "item", ...item, url: item.url || null } : { entity: "item", ...item, url: item.url || null }) }); setItem(blankItem); setItemId(null); await load(); setMessage("Contact detail saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save."); } }
  async function saveFaq(event: FormEvent) { event.preventDefault(); try { await request("/api/contact", { method: faqId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(faqId ? { id: faqId, entity: "faq", ...faq } : { entity: "faq", ...faq }) }); setFaq(blankFaq); setFaqId(null); await load(); setMessage("FAQ saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save."); } }
  async function remove(entity: "item" | "faq", id: string) { if (!confirm("Delete this item?")) return; try { await request(`/api/contact?entity=${entity}&id=${id}`, { method: "DELETE" }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not delete."); } }
  return <div><Message text={message} /><div className="grid lg:grid-cols-2 gap-8"><section><form onSubmit={saveItem} className="border border-[#d4a843]/20 bg-[#0d1f35]/60 p-6 mb-5"><h2 className="font-serif text-2xl mb-5">{itemId ? "Edit contact detail" : "Add contact detail"}</h2><div className="grid grid-cols-[80px_1fr] gap-3"><Field name="Icon"><input className={input} value={item.icon} onChange={(e) => setItem({ ...item, icon: e.target.value })} /></Field><Field name="Label"><input className={input} value={item.label} onChange={(e) => setItem({ ...item, label: e.target.value })} required /></Field></div><div className="mt-4"><Field name="Displayed value"><textarea className={input} value={item.value} onChange={(e) => setItem({ ...item, value: e.target.value })} required /></Field></div><div className="mt-4"><Field name="Clickable link (optional)"><input className={input} value={item.url} onChange={(e) => setItem({ ...item, url: e.target.value })} placeholder="mailto:… or https://…" /></Field></div><button disabled={!configured} className={`${save} mt-5`}>Save contact detail</button></form><div className="space-y-3">{items.map((entry) => <article key={entry.id} className="border border-[#d4a843]/15 p-4 flex justify-between gap-3"><div><strong>{entry.icon} {entry.label}</strong><p className="text-sm text-[#e8e8e0]/45 mt-1">{entry.value}</p></div><Actions edit={() => { setItemId(entry.id); setItem({ icon: entry.icon, label: entry.label, value: entry.value, url: entry.url || "", sort_order: entry.sort_order }); }} remove={() => remove("item", entry.id)} /></article>)}</div></section><section><form onSubmit={saveFaq} className="border border-[#d4a843]/20 bg-[#0d1f35]/60 p-6 mb-5"><h2 className="font-serif text-2xl mb-5">{faqId ? "Edit FAQ" : "Add an FAQ"}</h2><Field name="Question"><input className={input} value={faq.question} onChange={(e) => setFaq({ ...faq, question: e.target.value })} required /></Field><div className="mt-4"><Field name="Answer"><textarea className={`${input} min-h-24`} value={faq.answer} onChange={(e) => setFaq({ ...faq, answer: e.target.value })} required /></Field></div><button disabled={!configured} className={`${save} mt-5`}>Save FAQ</button></form><div className="space-y-3">{faqs.map((entry) => <article key={entry.id} className="border border-[#d4a843]/15 p-4 flex justify-between gap-3"><div><strong>{entry.question}</strong><p className="text-sm text-[#e8e8e0]/45 mt-1">{entry.answer}</p></div><Actions edit={() => { setFaqId(entry.id); setFaq({ question: entry.question, answer: entry.answer, sort_order: entry.sort_order }); }} remove={() => remove("faq", entry.id)} /></article>)}</div></section></div></div>;
}

export function QotdManager({ configured }: { configured: boolean }) {
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const blank = { question: "", display_date: today, topic: "", difficulty: "", note: "" };
  const [form, setForm] = useState(blank); const [id, setId] = useState<string | null>(null); const [items, setItems] = useState<QotdRecord[]>([]); const [message, setMessage] = useState("");
  const load = () => request("/api/qotd?all=1").then((data) => setItems(data.items)).catch((error) => setMessage(error.message)); useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); try { await request("/api/qotd", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(id ? { id, ...form } : form) }); setForm(blank); setId(null); await load(); setMessage("Question scheduled. It will appear on the homepage on its date."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save."); } }
  async function remove(item: QotdRecord) { if (!confirm("Delete this Question of the Day?")) return; try { await request(`/api/qotd?id=${item.id}`, { method: "DELETE" }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not delete."); } }
  return <div className="grid lg:grid-cols-[minmax(0,500px)_1fr] gap-8 items-start"><form onSubmit={submit} className="border border-[#d4a843]/20 bg-[#0d1f35]/60 p-6 lg:sticky lg:top-24"><h2 className="font-serif text-2xl mb-2">{id ? "Edit Question of the Day" : "Schedule Question of the Day"}</h2><p className="text-xs text-[#e8e8e0]/40 mb-5">The question is display-only. Visitors cannot submit answers or solutions.</p><Message text={message} /><Field name="Date"><input className={input} type="date" value={form.display_date} onChange={(e) => setForm({ ...form, display_date: e.target.value })} required /></Field><div className="mt-4"><Field name="Question"><textarea className={`${input} min-h-36`} value={form.question} onChange={(e) => setForm({ ...form, question: e.target.value })} required placeholder="Write the complete problem statement…" /></Field></div><div className="grid grid-cols-2 gap-3 mt-4"><Field name="Topic (optional)"><input className={input} value={form.topic} onChange={(e) => setForm({ ...form, topic: e.target.value })} /></Field><Field name="Difficulty (optional)"><input className={input} value={form.difficulty} onChange={(e) => setForm({ ...form, difficulty: e.target.value })} placeholder="Easy / Medium / Hard" /></Field></div><div className="mt-4"><Field name="Hint or note (optional)"><textarea className={input} value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></Field></div><button disabled={!configured} className={`${save} mt-5`}>{id ? "Save changes" : "Schedule question"}</button></form><div className="space-y-4"><h2 className="font-serif text-2xl">Scheduled questions ({items.length})</h2>{items.length === 0 && <p className="border border-[#d4a843]/10 p-8 text-center text-[#e8e8e0]/35">No questions scheduled yet.</p>}{items.map((item) => <article key={item.id} className="border border-[#d4a843]/15 bg-[#0d1f35]/40 p-5 flex justify-between gap-4"><div><div className="text-[10px] uppercase tracking-widest text-[#d4a843] mb-2">{item.display_date} {item.display_date === today ? "· Today" : ""}</div><p className="font-serif text-lg whitespace-pre-line">{item.question}</p><p className="text-xs text-[#e8e8e0]/40 mt-2">{[item.topic, item.difficulty].filter(Boolean).join(" · ")}</p></div><Actions edit={() => { setId(item.id); setForm({ question: item.question, display_date: item.display_date, topic: item.topic, difficulty: item.difficulty, note: item.note }); scrollTo({ top: 0, behavior: "smooth" }); }} remove={() => remove(item)} /></article>)}</div></div>;
}

function Field({ name, children }: { name: string; children: React.ReactNode }) { return <label><span className={label}>{name}</span>{children}</label>; }
